language: php

dist: trusty
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

git:
    depth: 1

compiler:
    - gcc
    - clang

env:
    global:
        - CFLAGS="-g3 -O0 -Wall -fvisibility=hidden"
        - ZEND_DONT_UNLOAD_MODULES=1
        - USE_ZEND_ALLOC=0
    matrix:
        - CC="ccache gcc"
        - CC="ccache clang"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - env: CC="ccache gcc"
          php: nightly
          compiler: gcc
        - env: CC="ccache clang"
          php: nightly
          compiler: clang

cache:
    apt: true
    ccache: true
    timeout: 691200
    directories:
        - vendor
        - $HOME/.ccache
        - $HOME/.composer/cache

install:
    - phpenv config-rm xdebug.ini || true
    - bash ./unit-tests/ci/install-travis
    - composer --prefer-source install

before_install:
    - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;

script:
    - php --ri "Zephir Parser"
    - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full --num-callers=20 $(phpenv which php) ./unit-tests/phpunit -c phpunit.xml.dist --debug unit-tests/

notifications:
    email:
        recipients:
            - build@phalconphp.com
        on_success: change
        on_failure: always

addons:
    apt:
        packages:
            - re2c
            - valgrind
            - gdb
