language: php

dist: trusty
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

git:
    depth: 1

compiler:
    - gcc
    - clang

env:
    global:
        - CFLAGS="-g3 -O0 -Wall -fvisibility=hidden"
        - ZEND_DONT_UNLOAD_MODULES=1
        - USE_ZEND_ALLOC=0
    matrix:
        - CC="gcc"
        - CC="clang"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - env: CC="gcc"
          php: nightly
          compiler: gcc
        - env: CC="clang"
          php: nightly
          compiler: clang

cache:
    apt: true
    timeout: 691200

install:
    - phpenv config-rm xdebug.ini || true
    - bash ./install-development

script:
    - |
      valgrind \
      --read-var-info=yes \
      --error-exitcode=1 \
      --fullpath-after= \
      --track-origins=yes \
      --leak-check=full \
            --num-callers=20 \
            --suppressions=$(pwd)/tests/zephir_parser.3.7.0.sup \
            $(phpenv which php) \
                -d variables_order=EGPCS \
                run-tests.php \
                -p $(which php) \
                -d extension=$(pwd)/modules/zephir_parser.so \
                -d variables_order=EGPCS \
                -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" \
                --offline \
                --show-diff \
                --set-timeout 120

notifications:
    email:
        recipients:
            - build@phalconphp.com
        on_success: change
        on_failure: always

addons:
    apt:
        packages:
            - re2c
            - valgrind
            - gdb
