language: php

dist: trusty
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

git:
    depth: 1

compiler:
    - gcc
    - clang

env:
    global:
        - CFLAGS="-g3 -O0 -Wall -fvisibility=hidden"
        - ZEND_DONT_UNLOAD_MODULES=1
        - USE_ZEND_ALLOC=0
    matrix:
        # Minimal re2c version
        - CC="gcc" RE2C_VERSION="0.13.6"
        - CC="clang" RE2C_VERSION="0.13.6"
        # Latest stable re2c version
        - CC="gcc" RE2C_VERSION="1.0.2"
        - CC="clang" RE2C_VERSION="1.0.2"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: 7.2
        - env: CC="gcc" RE2C_VERSION="1.0.2"
        - env: CC="clang" RE2C_VERSION="1.0.2"
    exclude:
        - env: CC="gcc"
          compiler: clang
        - env: CC="clang"
          compiler: gcc
    include:
        - env: CC="gcc"
          php: nightly
          compiler: gcc
        - env: CC="clang"
          php: nightly
          compiler: clang

cache:
    apt: true
    ccache: true
    timeout: 604800
    directories:
        - $HOME/.ccache
        - $HOME/.local/opt/re2c
        - $HOME/.cache/re2c

install:
    - phpenv config-rm xdebug.ini || true
    - bash ./install-re2c $RE2C_VERSION
    - bash ./install-development --phpize $(phpenv which phpize) --php-config $(phpenv which php-config) --install

script:
    - |
        valgrind \
            --read-var-info=yes \
            --error-exitcode=1 \
            --fullpath-after= \
            --track-origins=yes \
            --leak-check=full \
            --num-callers=20 \
            --suppressions=$(pwd)/tests/zephir_parser.3.7.0.sup \
            $(phpenv which php) \
                -d variables_order=EGPCS \
                run-tests.php \
                -p $(which php) \
                -d variables_order=EGPCS \
                -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" \
                --offline \
                --show-diff \
                --set-timeout 120

addons:
    apt:
        packages:
            - valgrind
            - gdb
