language: php

dist: trusty
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

git:
  depth: 1

compiler:
  - gcc
  - clang

env:
  global:
    - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LD_LIBRARY_PATH
    - LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LIBRARY_PATH
    - C_INCLUDE_PATH="$TRAVIS_BUILD_DIR/build/include"
  matrix:
    - CC="ccache gcc" CFLAGS="-g3 -O0 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"
    - CC="ccache clang" CFLAGS="-g3 -O0"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - env: CC="ccache gcc" CFLAGS="-g3 -O0 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"
      php: nightly
      compiler: gcc
    - env: CC="ccache clang" CFLAGS="-g3 -O0"
      php: nightly
      compiler: clang

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

install:
    - |
      cd $TRAVIS_BUILD_DIR/parser
      re2c -o scanner.c scanner.re
      ${CC} lemon.c -o lemon
      ./lemon -s parser.php5.lemon
      ./lemon -s parser.php7.lemon
      echo "#include <php.h>" > parser.c
      echo "#if PHP_VERSION_ID < 70000" >> parser.c
      cat parser.php5.c >> parser.c
      echo "#else" >> parser.c
      cat parser.php7.c >> parser.c
      echo "#endif" >> parser.c
      cat base.c >> parser.c
      sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
      sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
      cd $TRAVIS_BUILD_DIR
    - |
      $(phpenv which phpize)
      /configure --with-php-config=$(phpenv which php-config) --enable-zephir_parser
      make -j"$(getconf _NPROCESSORS_ONLN)"
      make install
      phpenv config-add zephir_parser.ini

before_install:
  - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;

script:
  - php --ri "Zephir Parser"

notifications:
  email:
    - build@phalconphp.com

addons:
  apt:
    packages:
      - re2c
      - valgrind
      - gdb
