language: php

dist: trusty
sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

git:
    depth: 1

compiler:
    - gcc
    - clang

env:
    global:
        - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LD_LIBRARY_PATH
        - LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LIBRARY_PATH
        - C_INCLUDE_PATH="$TRAVIS_BUILD_DIR/build/include"
    matrix:
        - CC="ccache gcc" CFLAGS="-g3 -O0 -fno-delete-null-pointer-checks -Wall -std=gnu90 -fvisibility=hidden"
        - CC="ccache clang" CFLAGS="-g3 -O0 -fcolor-diagnostics -Wall -std=gnu90"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - env: CC="ccache gcc" CFLAGS="-g3 -O0 -fno-delete-null-pointer-checks -Wall -std=gnu90 -fvisibility=hidden"
          php: nightly
          compiler: gcc
        - env: CC="ccache clang" CFLAGS="-g3 -O0 -fcolor-diagnostics -Wall -std=gnu90"
          php: nightly
          compiler: clang

cache:
    apt: true
    ccache: true
    timeout: 691200
    directories:
        - vendor
        - $HOME/.ccache
        - $HOME/.composer/cache

install:
    - bash ./tests/ci/install-travis

before_install:
    - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;

script:
    - php --ri "Zephir Parser"

notifications:
    email:
        - build@phalconphp.com

addons:
    apt:
        packages:
            - re2c
            - valgrind
            - gdb
